### ISSUE TITLE
Importing Published Apps - Published Name vs Name

### ISSUE THREAD

**Issue by joshtbernstein** [SLemonier/Citrix-Site-Import-Export#3]
The [import script](https://github.com/SLemonier/Citrix-Site-Import-Export/blob/main/Import-CitrixSite.ps1#L1052) seems to be using the wrong attribute for a published application's name.

I believe it should be:

`$command = "New-Brokerapplication -Name """ + $PublishedApp.Name + """"`

instead of:

`$command = "New-Brokerapplication -Name """ + $PublishedApp.PublishedName + """"`

**Comment by SLemonier** [comment]
Hello Josh,

You are right, I've updated the script.

Thank you for your feedback!
