### ISSUE TITLE
Use UserName (SAM name) instead of UserFullName

### ISSUE THREAD

**Issue by joshtbernstein** [SLemonier/Citrix-Site-Import-Export#4]
I'd recommend replacing `UserFullNames`/`UserFullName` with `UserNames`/`UserName` for Published Applications and Application Groups in the export and import scripts. This was failing for me on any published apps that had users assigned.

> AssociatedUserFullNames (System.String[]) List of associated users (full names). Associated users is the list of users who are given access using the application/user mapping filter.

> AssociatedUserNames (System.String[]) List of associated users (SAM names). Associated users is the list of users who are given access using the application/user mapping filter.

**Comment by SLemonier** [comment]
Yeah it makes more sense.

I replaced UserFullname(s) with UserName(s).
