### ISSUE TITLE
Published Application's name contains AdminFolderName

### ISSUE THREAD

**Issue by joshtbernstein** [SLemonier/Citrix-Site-Import-Export#5]
Last issue for now (sorry!). At least in my case (7.15 CU6), it looks like `Get-BrokerApplication` adds the `AdminFolderName` to the published application's `Name` which causes issues on import. For example an *My Application* in *Folder1* would store `Folder\My Application` in the name field in the exported XML file. I'd guess you would have to do a find/remove using `PublishedApp.AdminFolderName` on `PublishedApp.Name`

**Comment by SLemonier** [comment]
No worries, your feedback is much appreciated :)

This was the reason I chose to use published name instead of name when creating New-BrokerApplication. The folder is part of -AdminFolder parameter.

Either I go back to using Name. Or I remove the -AdminFolder part.

**Comment by joshtbernstein** [comment]
Using my previous example (a published application in a folder: `Folder1\My Application`). You'll end up with the following in `export.xml`:
```
<PublishedApp>
  <Name>Folder1\My Application</Name>
  <Description>
  </Description>
  <CommandLineExecutable>myapplication.exe</CommandLineExecutable>
  <CommandLineArguments>
  </CommandLineArguments>
  <WorkingDirectory>
  </WorkingDirectory>
  <PublishedName>My Application</PublishedName>
  <IconUid>1</IconUid>
  <AdminFolderName>Folder1\</AdminFolderName>
  <ApplicationName>My Application</ApplicationName>
  <ApplicationType>PublishedContent</ApplicationType>
  <AssociatedDesktopGroupName>Image1</AssociatedDesktopGroupName>
  <Enabled>False</Enabled>
  <MaxPerUserInstances>0</MaxPerUserInstances>
  <MaxTotalInstances>0</MaxTotalInstances>
  <ShortcutAddedToDesktop>False</ShortcutAddedToDesktop>
  <ShortcutAddedToStartMenu>False</ShortcutAddedToStartMenu>
  <StartMenuFolder>
  </StartMenuFolder>
  <UserFilterEnabled>False</UserFilterEnabled>
  <Visible>True</Visible>
</PublishedApp>
```

The import script then tries to run the following command: `New-Brokerapplication -Name "Folder1\My Application" -CommandLineExecutable "myapplication.exe" -DesktopGroup "Image1" -AdminFolder "Folder1\" -ApplicationType "PublishedContent" -CommandLineArguments "" -Description "" -Enabled $False -IconUid "1" -MaxPerUserInstances "0" -MaxTotalInstances "0" -PublishedName "My Application" -ShortcutAddedToDesktop $False -ShortcutAddedToStartMenu $False -StartMenuFolder "" -UserFilterEnabled $False -Visible $True -WorkingDirectory ""`.

The command fails, because the `-Name` parameter can't have a `\` in it. So I'm thinking that that the published application's `AdminFolder` value needs to be removed from the published application's `Name`, either when creating the XML or during the import. You'd end up with the following command: `New-Brokerapplication -Name "My Application ... -AdminFolder "Folder1\" ...`.

Hopefully this makes sense?

**Comment by SLemonier** [comment]
Isn't it easier to just use _<PublishedName>My Application</PublishedName>_ as _-Name_ parameter then?

**Comment by joshtbernstein** [comment]
I see what you're saying. The only issue is then you're back in the spot where `-PublishedName` doesn't have to be unique so you run into issues if you use that as `-Name`. Probably better to leave it as though.

**Comment by SLemonier** [comment]
$PublishedApp.Name replaced with:
```
$PublishedAppName = ($PublishedApp.Name).Split("\")[-1]
$command = "New-Brokerapplication -Name """ + $PublishedAppName + """"
```
